### ISSUE TITLE
flutter can't import lpinyin.dart

### ISSUE THREAD

**Issue by itlwy** [flutterchina/lpinyin#3]
flutter can't import lpinyin.dart，error as below:

Try correcting the name to the name of an existing getter, or defining a getter or field named 'PinyinHelper'.
        String pinyin = PinyinHelper.getPinyinE(user.userName);
                        ^^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Alpinyin%2Flpinyin.dart; message=StandardFileSystem only supports file:* 
and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)

#1      asFileUri (package:vm/kernel_front_end.dart:601:37)
<asynchronous suspension>
#2  
    FrontendCompiler._outputDependenciesDelta (package:vm/frontend_server.dart:401:39)
<asy
nchronous suspension>
#3      FrontendCompiler.compile (package:vm/frontend_server.dart:375:
13)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:frontend_ser
ver/server.dart:31:22)
<asynchronous suspension>
#5      starter (package:frontend_server/s
erver.dart:128:27)
<asynchronous suspension>
#6      main (file:///C:/b/s/w/ir/k/src/flutter/frontend_ser
ver/bin/starter.dart:8:30)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (
dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:i
solate-patch/isolate_patch.dart:172:12)

**Comment by itlwy** [comment]
Flutter 1.7.8+hotfix.4
please help,thanks

**Comment by Sky24n** [comment]
https://pub.dev/packages/lpinyin#-installing-tab-

**Comment by Sky24n** [comment]
```dart
Step 1：
dependencies:
  lpinyin: ^1.0.7

Step 2：
flutter packages get  
  
Step 3：
import 'package:lpinyin/lpinyin.dart';

String pinyin = PinyinHelper.getPinyinE(user.userName);
```

**Comment by itlwy** [comment]
This version of path_provider will break your Android build if it or its dependencies aren't compatible with AndroidX
