### ISSUE TITLE
getShortPinyin报错

### ISSUE THREAD

**Issue by dreamfly32** [flutterchina/lpinyin#5]
像  "a,b" 这种会报错，中间是英文逗号，我试了中文逗号，句号，英文句号等都可以，唯独英文逗号不行，这么什么问题？

The following RangeError was thrown while handling a gesture:
RangeError (index): Invalid value: Valid value range is empty: 0

When the exception was thrown, this was the stack: 
#0      _StringBase.[] (dart:core-patch/string_patch.dart:252:55)
#1      PinyinHelper.getShortPinyin.<anonymous closure> (package:lpinyin/src/pinyin_helper.dart:51:21)

**Comment by Sky24n** [comment]
你这都不是汉字怎么能拿来获取首拼呢


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Sky24n** [comment]
fix
