### ISSUE TITLE
Convert numbered pinyin to pinyin with tone marks

### ISSUE THREAD

**Issue by Cronos87** [flutterchina/lpinyin#8]
Hello!

Is it possible to convert a pinyin string using numbers to the one with tone marks?

ni3hao3 => nǐhǎo

Thank you for the help!

**Comment by matthewkooshad** [comment]
try this one for that feature: https://pub.dev/packages/pinyinizer

**Comment by Cronos87** [comment]
Perfect! Thank you for the suggestion!
